name: 'Run tests'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # Any checks that run pre-build
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      #-
      #  name: Start test infrastructure
      #  shell: bash
      #  run: |
      #    make setup
      -
        name: Run tests
        shell: bash
        run: |
          # make test
          TEST_ZONE_NAME=example.com. make test
          
